name: 'Dispatch Action'
description: 'dispatches action to target repo'
inputs:
  target:
    description: 'repo to dispatch action'
    required: true
    default: null
  event_type:
    description: 'event type to dispatch'
    required: false
    default: 'custom_event'
  client_payload:
    description: 'custom payload'
    required: false
    default: null
  token:
    description: 'auth token'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'lib/main.js'
